#!/bin/bash
STAGE_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.js')
if test ${#STAGE_FILES} -gt 0
then
	echo '開始eslint檢查'

	which eslint &> /dev/null
	if [[ "$?" == 1 ]]; then
		echo '沒安裝eslint'
		exit 1
	fi

	PASS=true

	for FILE in $STAGE_FILES
	do
		eslint $FILE
		if [[ "$?" == 1 ]]; then
  	  PASS=false
  	fi
  done

  if ! $PASS; then
	  echo "eslint檢查沒通過！"
	  exit 1
  else
	  echo "eslint檢查完畢"
  fi

else
	echo '沒有js檔案需要檢查'
fi

exit 0
